version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      #- cluster.name=elasticsearch
      #- node.name=es1
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      #- discovery.seed_hosts=es1
      #- cluster.initial_master_nodes=es1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ~/work/codeDir/dockerDemo/data/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ~/work/codeDir/dockerDemo/data/elasticsearch/data:/usr/share/elasticsearch/data
      - ~/work/codeDir/dockerDemo/data/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ~/work/codeDir/dockerDemo/data/elasticsearch/logs:/usr/share/elasticsearch/logs
    networks:
      - elk
  kibana: 
    image: kibana:7.7.0
    environment:  
      - I18N_LOCALE=zh-CN
      #- XPACK_GRAPH_ENABLED=true
      #- TIMELION_ENABLED=true
      #- XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - 5601:5601
    volumes:
      - ~/work/codeDir/dockerDemo/data/kibana:/etc/kibana
    networks:
      - elk
networks:
  elk:
    driver: bridge
